<?php

return [
    'permissions' => [
        ['kode' => 'dashboard.view', 'modul' => 'dashboard', 'aksi' => 'view', 'label' => 'Lihat Dashboard'],

        ['kode' => 'pos.antrian.view', 'modul' => 'pos.antrian', 'aksi' => 'view', 'label' => 'Lihat Input Antrian'],
        ['kode' => 'pos.input_order.read', 'modul' => 'pos.input_order', 'aksi' => 'read', 'label' => 'Lihat Input Order'],
        ['kode' => 'pos.input_order.create', 'modul' => 'pos.input_order', 'aksi' => 'create', 'label' => 'Simpan Input Order'],
        ['kode' => 'pos.transaksi.read', 'modul' => 'pos.transaksi', 'aksi' => 'read', 'label' => 'Lihat Transaksi Penjualan'],
        ['kode' => 'pos.transaksi.create', 'modul' => 'pos.transaksi', 'aksi' => 'create', 'label' => 'Simpan Transaksi Penjualan'],
        ['kode' => 'pos.transaksi.override_price', 'modul' => 'pos.transaksi', 'aksi' => 'authorize', 'label' => 'Otorisasi Perubahan Harga POS'],
        ['kode' => 'pos.transaksi.backdate', 'modul' => 'pos.transaksi', 'aksi' => 'create', 'label' => 'Input Transaksi Penjualan Backdate'],
        ['kode' => 'pos.tutup_kasir.view', 'modul' => 'pos.tutup_kasir', 'aksi' => 'read', 'label' => 'Lihat Tutup Kasir'],
        ['kode' => 'pos.tutup_kasir.close', 'modul' => 'pos.tutup_kasir', 'aksi' => 'update', 'label' => 'Proses Tutup Kasir'],
        ['kode' => 'pos.riwayat.read', 'modul' => 'pos.riwayat', 'aksi' => 'read', 'label' => 'Lihat Riwayat Penjualan'],
        ['kode' => 'pos.riwayat.reprint', 'modul' => 'pos.riwayat', 'aksi' => 'print', 'label' => 'Reprint Struk Riwayat Penjualan'],
        ['kode' => 'pos.riwayat.void', 'modul' => 'pos.riwayat', 'aksi' => 'void', 'label' => 'Void Transaksi Penjualan'],
        ['kode' => 'pos.riwayat.change_payment_method', 'modul' => 'pos.riwayat', 'aksi' => 'update', 'label' => 'Ganti Metode Pembayaran Riwayat Penjualan'],
        ['kode' => 'pos.riwayat.backdate', 'modul' => 'pos.riwayat', 'aksi' => 'read', 'label' => 'Filter Riwayat Penjualan Backdate'],
        ['kode' => 'pos.koreksi_transaksi.read', 'modul' => 'pos.koreksi_transaksi', 'aksi' => 'read', 'label' => 'Lihat Koreksi Transaksi'],
        ['kode' => 'pos.koreksi_transaksi.update', 'modul' => 'pos.koreksi_transaksi', 'aksi' => 'update', 'label' => 'Ubah Transaksi Customer'],
        ['kode' => 'pos.void_otp.read', 'modul' => 'pos.void_otp', 'aksi' => 'read', 'label' => 'Lihat Generate OTP Void'],
        ['kode' => 'pos.void_otp.generate', 'modul' => 'pos.void_otp', 'aksi' => 'create', 'label' => 'Generate OTP Void'],
        ['kode' => 'laporan.menu.view', 'modul' => 'laporan.menu', 'aksi' => 'view', 'label' => 'Lihat Menu Laporan'],
        ['kode' => 'laporan.penjualan.view', 'modul' => 'laporan.penjualan', 'aksi' => 'report', 'label' => 'Lihat Laporan Penjualan'],
        ['kode' => 'laporan.penjualan_paket.view', 'modul' => 'laporan.penjualan_paket', 'aksi' => 'report', 'label' => 'Lihat Laporan Penjualan Paket'],
        ['kode' => 'laporan.penjualan_barang_jasa.view', 'modul' => 'laporan.penjualan_barang_jasa', 'aksi' => 'report', 'label' => 'Lihat Laporan Penjualan Barang/Jasa'],
        ['kode' => 'laporan.booking.view', 'modul' => 'laporan.booking', 'aksi' => 'report', 'label' => 'Lihat Laporan Booking'],
        ['kode' => 'laporan.promosi.view', 'modul' => 'laporan.promosi', 'aksi' => 'report', 'label' => 'Lihat Laporan Promosi'],
        ['kode' => 'laporan.pembayaran.view', 'modul' => 'laporan.pembayaran', 'aksi' => 'report', 'label' => 'Lihat Laporan Pembayaran'],
        ['kode' => 'laporan.kasir.view', 'modul' => 'laporan.kasir', 'aksi' => 'report', 'label' => 'Lihat Laporan Kasir'],
        ['kode' => 'laporan.tutup_kasir.view', 'modul' => 'laporan.tutup_kasir', 'aksi' => 'report', 'label' => 'Lihat Laporan Tutup Kasir'],
        ['kode' => 'laporan.pembelian_pesanan.view', 'modul' => 'laporan.pembelian_pesanan', 'aksi' => 'report', 'label' => 'Lihat Laporan Pesanan Pembelian'],
        ['kode' => 'laporan.pembelian_penerimaan.view', 'modul' => 'laporan.pembelian_penerimaan', 'aksi' => 'report', 'label' => 'Lihat Laporan Penerimaan Barang'],
        ['kode' => 'laporan.pembelian_faktur.view', 'modul' => 'laporan.pembelian_faktur', 'aksi' => 'report', 'label' => 'Lihat Laporan Faktur Pembelian'],
        ['kode' => 'laporan.pembelian_pembayaran.view', 'modul' => 'laporan.pembelian_pembayaran', 'aksi' => 'report', 'label' => 'Lihat Laporan Pembayaran Pembelian'],
        ['kode' => 'laporan.pembelian_retur.view', 'modul' => 'laporan.pembelian_retur', 'aksi' => 'report', 'label' => 'Lihat Laporan Retur Pembelian'],
        ['kode' => 'laporan.performa_karyawan.view', 'modul' => 'laporan.performa_karyawan', 'aksi' => 'report', 'label' => 'Lihat Laporan Performa Karyawan'],

        ['kode' => 'paket.bom.read', 'modul' => 'paket.bom', 'aksi' => 'read', 'label' => 'Lihat BOM Paket'],
        ['kode' => 'paket.bom.create', 'modul' => 'paket.bom', 'aksi' => 'create', 'label' => 'Tambah BOM Paket'],
        ['kode' => 'paket.bom.update', 'modul' => 'paket.bom', 'aksi' => 'update', 'label' => 'Ubah BOM Paket'],
        ['kode' => 'paket.bom.delete', 'modul' => 'paket.bom', 'aksi' => 'delete', 'label' => 'Hapus BOM Paket'],

        ['kode' => 'paket.master.read', 'modul' => 'paket.master', 'aksi' => 'read', 'label' => 'Lihat Master Paket'],
        ['kode' => 'paket.master.create', 'modul' => 'paket.master', 'aksi' => 'create', 'label' => 'Tambah Master Paket'],
        ['kode' => 'paket.master.update', 'modul' => 'paket.master', 'aksi' => 'update', 'label' => 'Ubah Master Paket'],
        ['kode' => 'paket.master.delete', 'modul' => 'paket.master', 'aksi' => 'delete', 'label' => 'Hapus Master Paket'],

        ['kode' => 'paket.kategori.read', 'modul' => 'paket.kategori', 'aksi' => 'read', 'label' => 'Lihat Kategori Paket'],
        ['kode' => 'paket.kategori.create', 'modul' => 'paket.kategori', 'aksi' => 'create', 'label' => 'Tambah Kategori Paket'],
        ['kode' => 'paket.kategori.update', 'modul' => 'paket.kategori', 'aksi' => 'update', 'label' => 'Ubah Kategori Paket'],
        ['kode' => 'paket.kategori.delete', 'modul' => 'paket.kategori', 'aksi' => 'delete', 'label' => 'Hapus Kategori Paket'],

        ['kode' => 'paket.addon.read', 'modul' => 'paket.addon', 'aksi' => 'read', 'label' => 'Lihat Addon Paket'],
        ['kode' => 'paket.addon.create', 'modul' => 'paket.addon', 'aksi' => 'create', 'label' => 'Tambah Addon Paket'],
        ['kode' => 'paket.addon.update', 'modul' => 'paket.addon', 'aksi' => 'update', 'label' => 'Ubah Addon Paket'],
        ['kode' => 'paket.addon.delete', 'modul' => 'paket.addon', 'aksi' => 'delete', 'label' => 'Hapus Addon Paket'],

        ['kode' => 'paket.kategori_addon.read', 'modul' => 'paket.kategori_addon', 'aksi' => 'read', 'label' => 'Lihat Kategori Addon'],
        ['kode' => 'paket.kategori_addon.create', 'modul' => 'paket.kategori_addon', 'aksi' => 'create', 'label' => 'Tambah Kategori Addon'],
        ['kode' => 'paket.kategori_addon.update', 'modul' => 'paket.kategori_addon', 'aksi' => 'update', 'label' => 'Ubah Kategori Addon'],
        ['kode' => 'paket.kategori_addon.delete', 'modul' => 'paket.kategori_addon', 'aksi' => 'delete', 'label' => 'Hapus Kategori Addon'],

        ['kode' => 'template.harga.read', 'modul' => 'template.harga', 'aksi' => 'read', 'label' => 'Lihat Template Harga'],
        ['kode' => 'template.harga.create', 'modul' => 'template.harga', 'aksi' => 'create', 'label' => 'Tambah Template Harga'],
        ['kode' => 'template.harga.update', 'modul' => 'template.harga', 'aksi' => 'update', 'label' => 'Ubah Template Harga'],
        ['kode' => 'template.harga.delete', 'modul' => 'template.harga', 'aksi' => 'delete', 'label' => 'Hapus Template Harga'],

        ['kode' => 'sales_mode.read', 'modul' => 'sales_mode', 'aksi' => 'read', 'label' => 'Lihat Sales Mode'],
        ['kode' => 'sales_mode.create', 'modul' => 'sales_mode', 'aksi' => 'create', 'label' => 'Tambah Sales Mode'],
        ['kode' => 'sales_mode.update', 'modul' => 'sales_mode', 'aksi' => 'update', 'label' => 'Ubah Sales Mode'],
        ['kode' => 'sales_mode.delete', 'modul' => 'sales_mode', 'aksi' => 'delete', 'label' => 'Hapus Sales Mode'],

        ['kode' => 'promosi.read', 'modul' => 'promosi', 'aksi' => 'read', 'label' => 'Lihat Promosi'],
        ['kode' => 'promosi.create', 'modul' => 'promosi', 'aksi' => 'create', 'label' => 'Tambah Promosi'],
        ['kode' => 'promosi.update', 'modul' => 'promosi', 'aksi' => 'update', 'label' => 'Ubah Promosi'],
        ['kode' => 'promosi.delete', 'modul' => 'promosi', 'aksi' => 'delete', 'label' => 'Hapus Promosi'],
        ['kode' => 'tracking_order.view', 'modul' => 'tracking_order', 'aksi' => 'read', 'label' => 'Lihat Tracking Order'],

        ['kode' => 'konfigurasi.perusahaan.view', 'modul' => 'konfigurasi.perusahaan', 'aksi' => 'read', 'label' => 'Lihat Perusahaan'],
        ['kode' => 'konfigurasi.perusahaan.create', 'modul' => 'konfigurasi.perusahaan', 'aksi' => 'create', 'label' => 'Tambah Perusahaan'],
        ['kode' => 'konfigurasi.perusahaan.update', 'modul' => 'konfigurasi.perusahaan', 'aksi' => 'update', 'label' => 'Ubah Perusahaan'],
        ['kode' => 'konfigurasi.perusahaan.delete', 'modul' => 'konfigurasi.perusahaan', 'aksi' => 'delete', 'label' => 'Hapus Perusahaan'],
        ['kode' => 'konfigurasi.cabang.view', 'modul' => 'konfigurasi.cabang', 'aksi' => 'read', 'label' => 'Lihat Cabang'],
        ['kode' => 'konfigurasi.cabang.create', 'modul' => 'konfigurasi.cabang', 'aksi' => 'create', 'label' => 'Tambah Cabang'],
        ['kode' => 'konfigurasi.cabang.update', 'modul' => 'konfigurasi.cabang', 'aksi' => 'update', 'label' => 'Ubah Cabang'],
        ['kode' => 'konfigurasi.cabang.delete', 'modul' => 'konfigurasi.cabang', 'aksi' => 'delete', 'label' => 'Hapus Cabang'],
        ['kode' => 'konfigurasi.divisi.view', 'modul' => 'konfigurasi.divisi', 'aksi' => 'read', 'label' => 'Lihat Divisi'],
        ['kode' => 'konfigurasi.divisi.create', 'modul' => 'konfigurasi.divisi', 'aksi' => 'create', 'label' => 'Tambah Divisi'],
        ['kode' => 'konfigurasi.divisi.update', 'modul' => 'konfigurasi.divisi', 'aksi' => 'update', 'label' => 'Ubah Divisi'],
        ['kode' => 'konfigurasi.divisi.delete', 'modul' => 'konfigurasi.divisi', 'aksi' => 'delete', 'label' => 'Hapus Divisi'],
        ['kode' => 'konfigurasi.jabatan.view', 'modul' => 'konfigurasi.jabatan', 'aksi' => 'read', 'label' => 'Lihat Jabatan'],
        ['kode' => 'konfigurasi.jabatan.create', 'modul' => 'konfigurasi.jabatan', 'aksi' => 'create', 'label' => 'Tambah Jabatan'],
        ['kode' => 'konfigurasi.jabatan.update', 'modul' => 'konfigurasi.jabatan', 'aksi' => 'update', 'label' => 'Ubah Jabatan'],
        ['kode' => 'konfigurasi.jabatan.delete', 'modul' => 'konfigurasi.jabatan', 'aksi' => 'delete', 'label' => 'Hapus Jabatan'],
        ['kode' => 'konfigurasi.tracking.view', 'modul' => 'konfigurasi.tracking', 'aksi' => 'read', 'label' => 'Lihat Tracking'],
        ['kode' => 'konfigurasi.tracking.create', 'modul' => 'konfigurasi.tracking', 'aksi' => 'create', 'label' => 'Tambah Tracking'],
        ['kode' => 'konfigurasi.tracking.update', 'modul' => 'konfigurasi.tracking', 'aksi' => 'update', 'label' => 'Ubah Tracking'],
        ['kode' => 'konfigurasi.tracking.delete', 'modul' => 'konfigurasi.tracking', 'aksi' => 'delete', 'label' => 'Hapus Tracking'],
        ['kode' => 'konfigurasi.studio.view', 'modul' => 'konfigurasi.studio', 'aksi' => 'read', 'label' => 'Lihat Studio'],
        ['kode' => 'konfigurasi.studio.create', 'modul' => 'konfigurasi.studio', 'aksi' => 'create', 'label' => 'Tambah Studio'],
        ['kode' => 'konfigurasi.studio.update', 'modul' => 'konfigurasi.studio', 'aksi' => 'update', 'label' => 'Ubah Studio'],
        ['kode' => 'konfigurasi.studio.delete', 'modul' => 'konfigurasi.studio', 'aksi' => 'delete', 'label' => 'Hapus Studio'],
        ['kode' => 'konfigurasi.karyawan.read', 'modul' => 'konfigurasi.karyawan', 'aksi' => 'read', 'label' => 'Lihat Karyawan'],
        ['kode' => 'konfigurasi.karyawan.create', 'modul' => 'konfigurasi.karyawan', 'aksi' => 'create', 'label' => 'Tambah Karyawan'],
        ['kode' => 'konfigurasi.karyawan.update', 'modul' => 'konfigurasi.karyawan', 'aksi' => 'update', 'label' => 'Ubah Karyawan'],
        ['kode' => 'konfigurasi.karyawan.delete', 'modul' => 'konfigurasi.karyawan', 'aksi' => 'delete', 'label' => 'Hapus Karyawan'],
        ['kode' => 'konfigurasi.role_user.read', 'modul' => 'konfigurasi.role_user', 'aksi' => 'read', 'label' => 'Lihat Role User'],
        ['kode' => 'konfigurasi.role_user.create', 'modul' => 'konfigurasi.role_user', 'aksi' => 'create', 'label' => 'Tambah Role User'],
        ['kode' => 'konfigurasi.role_user.update', 'modul' => 'konfigurasi.role_user', 'aksi' => 'update', 'label' => 'Ubah Role User'],
        ['kode' => 'konfigurasi.role_user.delete', 'modul' => 'konfigurasi.role_user', 'aksi' => 'delete', 'label' => 'Hapus Role User'],

        ['kode' => 'persediaan.barang_jasa.read', 'modul' => 'persediaan.barang_jasa', 'aksi' => 'read', 'label' => 'Lihat Barang/Jasa'],
        ['kode' => 'persediaan.barang_jasa.create', 'modul' => 'persediaan.barang_jasa', 'aksi' => 'create', 'label' => 'Tambah Barang/Jasa'],
        ['kode' => 'persediaan.barang_jasa.update', 'modul' => 'persediaan.barang_jasa', 'aksi' => 'update', 'label' => 'Ubah Barang/Jasa'],
        ['kode' => 'persediaan.barang_jasa.delete', 'modul' => 'persediaan.barang_jasa', 'aksi' => 'delete', 'label' => 'Hapus Barang/Jasa'],

        ['kode' => 'persediaan.satuan.read', 'modul' => 'persediaan.satuan', 'aksi' => 'read', 'label' => 'Lihat Satuan'],
        ['kode' => 'persediaan.satuan.create', 'modul' => 'persediaan.satuan', 'aksi' => 'create', 'label' => 'Tambah Satuan'],
        ['kode' => 'persediaan.satuan.update', 'modul' => 'persediaan.satuan', 'aksi' => 'update', 'label' => 'Ubah Satuan'],
        ['kode' => 'persediaan.satuan.delete', 'modul' => 'persediaan.satuan', 'aksi' => 'delete', 'label' => 'Hapus Satuan'],

        ['kode' => 'persediaan.golongan.read', 'modul' => 'persediaan.golongan', 'aksi' => 'read', 'label' => 'Lihat Golongan'],
        ['kode' => 'persediaan.golongan.create', 'modul' => 'persediaan.golongan', 'aksi' => 'create', 'label' => 'Tambah Golongan'],
        ['kode' => 'persediaan.golongan.update', 'modul' => 'persediaan.golongan', 'aksi' => 'update', 'label' => 'Ubah Golongan'],
        ['kode' => 'persediaan.golongan.delete', 'modul' => 'persediaan.golongan', 'aksi' => 'delete', 'label' => 'Hapus Golongan'],
        ['kode' => 'persediaan.stok.read', 'modul' => 'persediaan.stok', 'aksi' => 'read', 'label' => 'Lihat Stok'],
        ['kode' => 'persediaan.stok.penyesuaian.update', 'modul' => 'persediaan.stok.penyesuaian', 'aksi' => 'update', 'label' => 'Edit Penyesuaian Stok'],

        ['kode' => 'permintaan_barang.read', 'modul' => 'permintaan_barang', 'aksi' => 'read', 'label' => 'Lihat Permintaan Barang'],
        ['kode' => 'permintaan_barang.create', 'modul' => 'permintaan_barang', 'aksi' => 'create', 'label' => 'Tambah Permintaan Barang'],
        ['kode' => 'permintaan_barang.update', 'modul' => 'permintaan_barang', 'aksi' => 'update', 'label' => 'Ubah Permintaan Barang'],
        ['kode' => 'permintaan_barang.delete', 'modul' => 'permintaan_barang', 'aksi' => 'delete', 'label' => 'Hapus Permintaan Barang'],

        ['kode' => 'pemasok.read', 'modul' => 'pemasok', 'aksi' => 'read', 'label' => 'Lihat Pemasok'],
        ['kode' => 'pemasok.create', 'modul' => 'pemasok', 'aksi' => 'create', 'label' => 'Tambah Pemasok'],
        ['kode' => 'pemasok.update', 'modul' => 'pemasok', 'aksi' => 'update', 'label' => 'Ubah Pemasok'],
        ['kode' => 'pemasok.delete', 'modul' => 'pemasok', 'aksi' => 'delete', 'label' => 'Hapus Pemasok'],

        ['kode' => 'pembelian.pesanan.read', 'modul' => 'pembelian.pesanan', 'aksi' => 'read', 'label' => 'Lihat Pesanan Pembelian'],
        ['kode' => 'pembelian.pesanan.create', 'modul' => 'pembelian.pesanan', 'aksi' => 'create', 'label' => 'Tambah Pesanan Pembelian'],
        ['kode' => 'pembelian.pesanan.update', 'modul' => 'pembelian.pesanan', 'aksi' => 'update', 'label' => 'Ubah Pesanan Pembelian'],
        ['kode' => 'pembelian.pesanan.delete', 'modul' => 'pembelian.pesanan', 'aksi' => 'delete', 'label' => 'Hapus Pesanan Pembelian'],
        ['kode' => 'pembelian.pesanan.close', 'modul' => 'pembelian.pesanan', 'aksi' => 'update', 'label' => 'Close Pesanan Pembelian'],

        ['kode' => 'pembelian.penerimaan.read', 'modul' => 'pembelian.penerimaan', 'aksi' => 'read', 'label' => 'Lihat Penerimaan Barang'],
        ['kode' => 'pembelian.penerimaan.create', 'modul' => 'pembelian.penerimaan', 'aksi' => 'create', 'label' => 'Tambah Penerimaan Barang'],
        ['kode' => 'pembelian.faktur.read', 'modul' => 'pembelian.faktur', 'aksi' => 'read', 'label' => 'Lihat Faktur Pembelian'],
        ['kode' => 'pembelian.faktur.create', 'modul' => 'pembelian.faktur', 'aksi' => 'create', 'label' => 'Tambah Faktur Pembelian'],
        ['kode' => 'pembelian.pembayaran.read', 'modul' => 'pembelian.pembayaran', 'aksi' => 'read', 'label' => 'Lihat Pembayaran Pembelian'],
        ['kode' => 'pembelian.pembayaran.create', 'modul' => 'pembelian.pembayaran', 'aksi' => 'create', 'label' => 'Tambah Pembayaran Pembelian'],
        ['kode' => 'pembelian.retur.read', 'modul' => 'pembelian.retur', 'aksi' => 'read', 'label' => 'Lihat Retur Pembelian'],
        ['kode' => 'pembelian.retur.create', 'modul' => 'pembelian.retur', 'aksi' => 'create', 'label' => 'Tambah Retur Pembelian'],
        ['kode' => 'pembelian.kategori_pemasok.view', 'modul' => 'pembelian.kategori_pemasok', 'aksi' => 'read', 'label' => 'Lihat Kategori Pemasok'],

        ['kode' => 'finance.coa.view', 'modul' => 'finance.coa', 'aksi' => 'read', 'label' => 'Lihat COA'],
        ['kode' => 'finance.tax.view', 'modul' => 'finance.tax', 'aksi' => 'read', 'label' => 'Lihat Tax'],
        ['kode' => 'finance.metode_pembayaran.view', 'modul' => 'finance.metode_pembayaran', 'aksi' => 'read', 'label' => 'Lihat Metode Pembayaran'],
        ['kode' => 'finance.metode_pembayaran.create', 'modul' => 'finance.metode_pembayaran', 'aksi' => 'create', 'label' => 'Tambah Metode Pembayaran'],
        ['kode' => 'finance.metode_pembayaran.update', 'modul' => 'finance.metode_pembayaran', 'aksi' => 'update', 'label' => 'Ubah Metode Pembayaran'],
        ['kode' => 'finance.metode_pembayaran.delete', 'modul' => 'finance.metode_pembayaran', 'aksi' => 'delete', 'label' => 'Hapus Metode Pembayaran'],

        ['kode' => 'produksi.pekerjaan_dg.view', 'modul' => 'produksi.pekerjaan_dg', 'aksi' => 'read', 'label' => 'Lihat Pekerjaan DG'],
        ['kode' => 'produksi.daftar_qc.view', 'modul' => 'produksi.daftar_qc', 'aksi' => 'read', 'label' => 'Lihat Daftar QC'],
        ['kode' => 'studio.antrian.view', 'modul' => 'studio.antrian', 'aksi' => 'read', 'label' => 'Lihat Antrian Studio'],
        ['kode' => 'studio.display_customer.view', 'modul' => 'studio.display_customer', 'aksi' => 'read', 'label' => 'Lihat Display Antrian Customer'],
        ['kode' => 'studio.audio_announcer.view', 'modul' => 'studio.audio_announcer', 'aksi' => 'read', 'label' => 'Lihat Audio Announcer Studio'],
        ['kode' => 'cs.konfirmasi.view', 'modul' => 'cs.konfirmasi', 'aksi' => 'read', 'label' => 'Lihat Konfirmasi'],
        ['kode' => 'cs.documentation.view', 'modul' => 'cs.documentation', 'aksi' => 'read', 'label' => 'Lihat Documentation'],
        ['kode' => 'cs.support.view', 'modul' => 'cs.support', 'aksi' => 'read', 'label' => 'Lihat Support'],
    ],

    'route_permission_map' => [
        'dashboard' => 'dashboard.view',
        'active-cabang.update' => 'dashboard.view',
        'input-antrian' => 'pos.antrian.view',
        'input-antrian.ko-search' => 'pos.antrian.view',
        'input-antrian.enqueue' => 'pos.antrian.view',
        'input-antrian.reorder' => 'pos.antrian.view',
        'input-antrian.delete' => 'pos.antrian.view',
        'input-order' => 'pos.input_order.read',
        'input-order.produk-cari' => 'pos.input_order.read',
        'input-order.cek-ko' => 'pos.input_order.read',
        'input-order.promosi-tersedia' => 'pos.input_order.read',
        'input-order.simpan' => 'pos.input_order.create',
        'transaksi-penjualan' => 'pos.transaksi.read',
        'transaksi-penjualan.produk-cari' => 'pos.transaksi.read',
        'transaksi-penjualan.cek-ko' => 'pos.transaksi.read',
        'transaksi-penjualan.promosi-tersedia' => 'pos.transaksi.read',
        'transaksi-penjualan.simpan' => 'pos.transaksi.create',
        'transaksi-penjualan.struk' => 'pos.transaksi.create',
        'pos.authorize-price-override' => 'pos.transaksi.read',
        'pos.tutup-kasir' => 'pos.tutup_kasir.view',
        'pos.tutup-kasir.open' => 'pos.tutup_kasir.close',
        'pos.tutup-kasir.close' => 'pos.tutup_kasir.close',
        'riwayat-penjualan' => 'pos.riwayat.read',
        'riwayat-penjualan.detail' => 'pos.riwayat.read',
        'riwayat-penjualan.reprint' => 'pos.riwayat.reprint',
        'riwayat-penjualan.void' => 'pos.riwayat.void',
        'riwayat-penjualan.payment-method.update' => 'pos.riwayat.change_payment_method',
        'koreksi-transaksi-penjualan' => 'pos.koreksi_transaksi.read',
        'koreksi-transaksi-penjualan.update' => 'pos.koreksi_transaksi.update',
        'pos.void-otp' => 'pos.void_otp.read',
        'pos.void-otp.cari-order' => 'pos.void_otp.read',
        'pos.void-otp.generate' => 'pos.void_otp.generate',
        'laporan.menu' => 'laporan.menu.view',
        'laporan-penjualan' => 'laporan.penjualan.view',
        'laporan-penjualan-paket' => 'laporan.penjualan_paket.view',
        'laporan-penjualan-barang-jasa' => 'laporan.penjualan_barang_jasa.view',
        'laporan-booking' => 'laporan.booking.view',
        'laporan-promosi' => 'laporan.promosi.view',
        'laporan-pembayaran' => 'laporan.pembayaran.view',
        'laporan-kasir' => 'laporan.kasir.view',
        'laporan-kasir-detail' => 'laporan.kasir.view',
        'laporan-performa-karyawan' => 'laporan.performa_karyawan.view',
        'laporan-tutup-kasir' => 'laporan.tutup_kasir.view',
        'laporan-tutup-kasir.resend-email' => 'laporan.tutup_kasir.view',
        'laporan-pembelian-pesanan' => 'laporan.pembelian_pesanan.view',
        'laporan-pembelian-penerimaan' => 'laporan.pembelian_penerimaan.view',
        'laporan-pembelian-faktur' => 'laporan.pembelian_faktur.view',
        'laporan-pembelian-pembayaran' => 'laporan.pembelian_pembayaran.view',
        'laporan-pembelian-retur' => 'laporan.pembelian_retur.view',

        'paket.bom' => 'paket.bom.read',
        'paket.bom.store' => 'paket.bom.create',
        'paket.bom.update' => 'paket.bom.update',
        'paket.bom.destroy' => 'paket.bom.delete',
        'paket.list' => 'paket.master.read',
        'paket.produk-cari' => 'paket.master.read',
        'paket.store' => 'paket.master.create',
        'paket.batch-status' => 'paket.master.update',
        'paket.update' => 'paket.master.update',
        'paket.destroy' => 'paket.master.delete',
        'paket.kategori' => 'paket.kategori.read',
        'paket.kategori.store' => 'paket.kategori.create',
        'paket.kategori.update' => 'paket.kategori.update',
        'paket.kategori.destroy' => 'paket.kategori.delete',
        'paket.addon' => 'paket.addon.read',
        'paket.addon.store' => 'paket.addon.create',
        'paket.addon.update' => 'paket.addon.update',
        'paket.addon.destroy' => 'paket.addon.delete',
        'paket.kategori-addon' => 'paket.kategori_addon.read',
        'paket.kategori-addon.store' => 'paket.kategori_addon.create',
        'paket.kategori-addon.update' => 'paket.kategori_addon.update',
        'paket.kategori-addon.destroy' => 'paket.kategori_addon.delete',
        'template.harga' => 'template.harga.read',
        'template.harga.store' => 'template.harga.create',
        'template.harga.update' => 'template.harga.update',
        'template.harga.destroy' => 'template.harga.delete',
        'template.harga.detail' => 'template.harga.read',
        'template.harga.copy-source' => 'template.harga.read',
        'template.harga.detail.simpan' => 'template.harga.update',

        'sales-mode' => 'sales_mode.read',
        'sales-mode.store' => 'sales_mode.create',
        'sales-mode.update' => 'sales_mode.update',
        'sales-mode.destroy' => 'sales_mode.delete',
        'promosi' => 'promosi.read',
        'promosi.voucher.store' => 'promosi.create',
        'promosi.voucher.update' => 'promosi.update',
        'promosi.voucher.destroy' => 'promosi.delete',
        'promosi.diskon.store' => 'promosi.create',
        'promosi.diskon.update' => 'promosi.update',
        'promosi.diskon.destroy' => 'promosi.delete',
        'tracking-order' => 'tracking_order.view',
        'tracking-order.ko-check.update' => 'tracking_order.view',
        'tracking-order.item-check.update' => 'tracking_order.view',

        'perusahaan.index' => 'konfigurasi.perusahaan.view',
        'cabang.index' => 'konfigurasi.cabang.view',
        'konfigurasi.divisi' => 'konfigurasi.divisi.view',
        'konfigurasi.divisi.store' => 'konfigurasi.divisi.create',
        'konfigurasi.divisi.update' => 'konfigurasi.divisi.update',
        'konfigurasi.divisi.destroy' => 'konfigurasi.divisi.delete',
        'konfigurasi.jabatan' => 'konfigurasi.jabatan.view',
        'konfigurasi.jabatan.store' => 'konfigurasi.jabatan.create',
        'konfigurasi.jabatan.update' => 'konfigurasi.jabatan.update',
        'konfigurasi.jabatan.destroy' => 'konfigurasi.jabatan.delete',
        'konfigurasi.jabatan.tracking-ko' => 'konfigurasi.jabatan.update',
        'konfigurasi.jabatan.tracking-ko.update' => 'konfigurasi.jabatan.update',
        'konfigurasi.tracking' => 'konfigurasi.tracking.view',
        'konfigurasi.tracking.store' => 'konfigurasi.tracking.create',
        'konfigurasi.tracking.update' => 'konfigurasi.tracking.update',
        'konfigurasi.tracking.destroy' => 'konfigurasi.tracking.delete',
        'konfigurasi.studio' => 'konfigurasi.studio.view',
        'konfigurasi.karyawan' => 'konfigurasi.karyawan.read',
        'konfigurasi.karyawan.create' => 'konfigurasi.karyawan.create',
        'konfigurasi.karyawan.store' => 'konfigurasi.karyawan.create',
        'konfigurasi.karyawan.edit' => 'konfigurasi.karyawan.update',
        'konfigurasi.karyawan.update' => 'konfigurasi.karyawan.update',
        'konfigurasi.karyawan.destroy' => 'konfigurasi.karyawan.delete',
        'konfigurasi.role-karyawan' => 'konfigurasi.role_user.read',
        'konfigurasi.role-karyawan.create' => 'konfigurasi.role_user.create',
        'konfigurasi.role-karyawan.store' => 'konfigurasi.role_user.create',
        'konfigurasi.role-karyawan.edit' => 'konfigurasi.role_user.update',
        'konfigurasi.role-karyawan.update' => 'konfigurasi.role_user.update',
        'konfigurasi.role-karyawan.destroy' => 'konfigurasi.role_user.delete',

        'persediaan.barang-jasa' => 'persediaan.barang_jasa.read',
        'persediaan.barang-jasa.store' => 'persediaan.barang_jasa.create',
        'persediaan.barang-jasa.batch-update' => 'persediaan.barang_jasa.update',
        'persediaan.barang-jasa.update' => 'persediaan.barang_jasa.update',
        'persediaan.barang-jasa.destroy' => 'persediaan.barang_jasa.delete',
        'persediaan.satuan' => 'persediaan.satuan.read',
        'persediaan.satuan.store' => 'persediaan.satuan.create',
        'persediaan.satuan.update' => 'persediaan.satuan.update',
        'persediaan.satuan.destroy' => 'persediaan.satuan.delete',
        'persediaan.golongan' => 'persediaan.golongan.read',
        'persediaan.golongan.store' => 'persediaan.golongan.create',
        'persediaan.golongan.update' => 'persediaan.golongan.update',
        'persediaan.golongan.destroy' => 'persediaan.golongan.delete',
        'persediaan.stok' => 'persediaan.stok.read',
        'persediaan.stok.penyesuaian' => 'persediaan.stok.read',
        'persediaan.stok.penyesuaian.create' => 'persediaan.stok.read',
        'persediaan.stok.penyesuaian.show' => 'persediaan.stok.read',
        'persediaan.stok.penyesuaian.edit' => 'persediaan.stok.penyesuaian.update',
        'persediaan.stok.penyesuaian.produk-cari' => 'persediaan.stok.read',
        'persediaan.stok.penyesuaian.store' => 'persediaan.stok.read',
        'persediaan.stok.penyesuaian.update' => 'persediaan.stok.penyesuaian.update',
        'persediaan.stok.penyesuaian.destroy' => 'persediaan.stok.read',

        'permintaan-barang.index' => 'permintaan_barang.read',
        'permintaan-barang.show' => 'permintaan_barang.read',
        'permintaan-barang.pdf' => 'permintaan_barang.read',
        'permintaan-barang.create' => 'permintaan_barang.create',
        'permintaan-barang.store' => 'permintaan_barang.create',
        'permintaan-barang.edit' => 'permintaan_barang.update',
        'permintaan-barang.update' => 'permintaan_barang.update',
        'permintaan-barang.destroy' => 'permintaan_barang.delete',

        'pemasok.index' => 'pemasok.read',
        'pemasok.create' => 'pemasok.create',
        'pemasok.store' => 'pemasok.create',
        'pemasok.edit' => 'pemasok.update',
        'pemasok.update' => 'pemasok.update',
        'pemasok.destroy' => 'pemasok.delete',

        'pembelian.pesanan' => 'pembelian.pesanan.read',
        'pembelian.pesanan.show' => 'pembelian.pesanan.read',
        'pembelian.pesanan.pdf' => 'pembelian.pesanan.read',
        'pembelian.pesanan.create' => 'pembelian.pesanan.create',
        'pembelian.pesanan.store' => 'pembelian.pesanan.create',
        'pembelian.pesanan.edit' => 'pembelian.pesanan.update',
        'pembelian.pesanan.update' => 'pembelian.pesanan.update',
        'pembelian.pesanan.close' => 'pembelian.pesanan.close',
        'pembelian.pesanan.destroy' => 'pembelian.pesanan.delete',

        'pembelian.penerimaan' => 'pembelian.penerimaan.read',
        'pembelian.penerimaan.show' => 'pembelian.penerimaan.read',
        'pembelian.penerimaan.pdf' => 'pembelian.penerimaan.read',
        'pembelian.penerimaan.create' => 'pembelian.penerimaan.create',
        'pembelian.penerimaan.store' => 'pembelian.penerimaan.create',

        'pembelian.faktur' => 'pembelian.faktur.read',
        'pembelian.faktur.show' => 'pembelian.faktur.read',
        'pembelian.faktur.pdf' => 'pembelian.faktur.read',
        'pembelian.faktur.create' => 'pembelian.faktur.create',
        'pembelian.faktur.store' => 'pembelian.faktur.create',

        'pembelian.pembayaran' => 'pembelian.pembayaran.read',
        'pembelian.pembayaran.show' => 'pembelian.pembayaran.read',
        'pembelian.pembayaran.pdf' => 'pembelian.pembayaran.read',
        'pembelian.pembayaran.store' => 'pembelian.pembayaran.create',

        'pembelian.retur' => 'pembelian.retur.read',
        'pembelian.retur.show' => 'pembelian.retur.read',
        'pembelian.retur.pdf' => 'pembelian.retur.read',
        'pembelian.retur.create' => 'pembelian.retur.create',
        'pembelian.retur.store' => 'pembelian.retur.create',
        'pembelian.kategori-pemasok' => 'pembelian.kategori_pemasok.view',

        'coa' => 'finance.coa.view',
        'tax' => 'finance.tax.view',
        'metode-pembayaran' => 'finance.metode_pembayaran.view',
        'metode-pembayaran.store' => 'finance.metode_pembayaran.create',
        'metode-pembayaran.update' => 'finance.metode_pembayaran.update',
        'metode-pembayaran.destroy' => 'finance.metode_pembayaran.delete',
        'pekerjaan-dg' => 'produksi.pekerjaan_dg.view',
        'pekerjaan-dg.mark-done' => 'produksi.pekerjaan_dg.view',
        'daftar-qc' => 'produksi.daftar_qc.view',
        'antrian-studio' => 'studio.antrian.view',
        'antrian-studio.board' => 'studio.antrian.view',
        'antrian-studio.stream' => 'studio.antrian.view',
        'antrian-studio.display.customer' => 'studio.display_customer.view',
        'antrian-studio.display.customer.board' => 'studio.display_customer.view',
        'antrian-studio.display.customer.stream' => 'studio.display_customer.view',
        'antrian-studio.audio-announcer' => 'studio.audio_announcer.view',
        'antrian-studio.audio-announcer.board' => 'studio.audio_announcer.view',
        'antrian-studio.audio-announcer.stream' => 'studio.audio_announcer.view',
        'antrian-studio.call' => 'studio.antrian.view',
        'antrian-studio.start' => 'studio.antrian.view',
        'antrian-studio.end' => 'studio.antrian.view',
        'antrian-studio.tugas.toggle' => 'studio.antrian.view',
        'antrian-studio.tracking-detail' => 'studio.antrian.view',
        'antrian-studio.tracking-item-check' => 'studio.antrian.view',
        'konfirmasi' => 'cs.konfirmasi.view',
        'konfirmasi.ko-check.update' => 'cs.konfirmasi.view',
        'documentation' => 'cs.documentation.view',
        'support' => 'cs.support.view',
        'sync-control' => 'dashboard.view',
        'sync-control.manual-push' => 'dashboard.view',
        'sync-control.manual-bootstrap' => 'dashboard.view',

        'konfigurasi.perusahaan.data.generate-kode' => 'konfigurasi.perusahaan.create',
        'konfigurasi.perusahaan.data.index' => 'konfigurasi.perusahaan.view',
        'konfigurasi.perusahaan.data.show' => 'konfigurasi.perusahaan.view',
        'konfigurasi.perusahaan.data.store' => 'konfigurasi.perusahaan.create',
        'konfigurasi.perusahaan.data.update' => 'konfigurasi.perusahaan.update',
        'konfigurasi.perusahaan.data.destroy' => 'konfigurasi.perusahaan.delete',

        'konfigurasi.cabang.data.index' => 'konfigurasi.cabang.view',
        'konfigurasi.cabang.data.perusahaan-list' => 'konfigurasi.cabang.view',
        'konfigurasi.cabang.data.sales-mode-template-list' => 'konfigurasi.cabang.view',
        'konfigurasi.cabang.data.generate-kode' => 'konfigurasi.cabang.create',
        'konfigurasi.cabang.data.show' => 'konfigurasi.cabang.view',
        'konfigurasi.cabang.data.store' => 'konfigurasi.cabang.create',
        'konfigurasi.cabang.data.update' => 'konfigurasi.cabang.update',
        'konfigurasi.cabang.data.destroy' => 'konfigurasi.cabang.delete',

        'konfigurasi.studio.data.index' => 'konfigurasi.studio.view',
        'konfigurasi.studio.data.cabang-list' => 'konfigurasi.studio.view',
        'konfigurasi.studio.data.tema-studio-list' => 'konfigurasi.studio.view',
        'konfigurasi.studio.data.show' => 'konfigurasi.studio.view',
        'konfigurasi.studio.data.store' => 'konfigurasi.studio.create',
        'konfigurasi.studio.data.update' => 'konfigurasi.studio.update',
        'konfigurasi.studio.data.destroy' => 'konfigurasi.studio.delete',
    ],
];
